clients:
 Tellurium: # Name of the computer - can be anything, doesn't need to match hostname
  ip: Tellurium.local # IP address or hostname used to connect to the client.
  mac: de:ad:be:ef:00:00 # MAC address. Only used for waking up the client. Doesn't need to be specified when 'wake' is 'no'
  wake: yes # yes/no. Says if the client should be woken up using Wake on LAN.
  username: satcom886 # Username used to connect with SSH.
 Argon:
  ip: Argon.local
  mac: 00:00:00:00:00:00
  wake: yes
  username: satcom886

command: "echo \"Hello from the other side!\" && sleep 5 && sudo systemctl poweroff" # Command that will be executed on all clients.